import React, { createContext, useContext, useState } from "react";

const translations = {
  EN: {
    // ── HEADER ──────────────────────────────────────────────
    nav_products: "Products", nav_services: "Services", nav_software: "Software",
    nav_applications: "Applications", nav_learn: "Learn", nav_support: "Support",
    nav_contact: "Contact", find_reseller: "Find a Reseller",

    // ── FOOTER ──────────────────────────────────────────────
    enter_email: "Enter your email address for updates",
    email_placeholder: "Business email", copyright: "© MYACCESS 2021",
    privacy: "Privacy Policy", terms: "Terms of Service", faq: "FAQ",
    footer_3dprinters: "3D Farm", footer_postprocess: "How We Work",
    footer_materials: "Services", footer_software: "Software",
    footer_industries: "Products", footer_learn: "Learn",
    footer_company: "Company", footer_support: "Support", footer_sales: "Sales",

    // ── CONTACT PAGE ────────────────────────────────────────
    contact_title: "Get in touch with us",
    contact_sales_title: "Contact Sales",
    contact_sales_desc: "Our experts are ready to help you find the right automation solutions to scale your business efficiency around the world.",
    find_reseller_btn: "Find a Local Reseller >",
    contact_support_title: "Contact Support",
    contact_support_desc: "If you have questions about using our products, please check out our support resources or reach out to us below.",
    visit_support: "Visit Our Support Site >", create_ticket: "Create a Support Ticket >",
    contact_general_title: "Contact MYACCESS",
    contact_general_desc: "Want to share feedback on your MYACCESS experience with us? We're listening and ready to assist with general inquiries.",
    submit_feedback: "Submit Feedback >", offices: "Offices", show_on_map: "Show on Map >",

    // ── INDUSTRIES PAGE ─────────────────────────────────────
    ind_headline: "Integrated Engineering & Manufacturing Solutions for Modern Hardware",
    ind_subtext: "From rapid prototyping to mass production, we provide end-to-end technical expertise. We bridge the gap between complex ideas and market-ready products with a focus on precision, scalability, and cost-efficiency.",
    select_industry: "Explore Our Expertise", learn_more: "View Service Details",
    ind_banner_title: "Need a technical roadmap for your project?",
    ind_banner_sub: "Speak with our senior engineers for a free feasibility audit and project consultation",
    scaling_title: "Accelerate Your Product Development Lifecycle",
    scaling_sub: "Whether you are a startup building your first MVP or an enterprise scaling to thousands of units, our infrastructure supports your growth at every stage.",
    explore_printers: "View Our Capabilities",find_reseller1:"Talk to an Expert",
    ind_solder_rework: "Soldering & Rework", ind_pcb_design: "PCB Design", ind_embedded_development: "Embedded Development",
    ind_test_debug: "Testing & Debugging", ind_compliance_checklist: "ESD Compliance Checklist", ind_mechanical_cad: "Mechanical CAD",
    ind_opencpu_firm: "OpenCPU / OpenWRT Firmware", ind_pcb_fabrication: "PCB Fabrication (Local/Global)", ind_component_procurement: "Component Procurement", ind_ems_assembly: "EMS Assembly",
    ind_3d:"3D Printing",ind_plastic:"Plastic Injection Molding (PIM)",ind_3d_mold:"3D Printed Mold (Prototype → Fabrication pipeline)",ind_mob:"Fullstack Development (Web + Mobile)",
    ind_cld_service:"Cloud Services",ind_cicd:"CI/CD & DevOps",ind_patent_filing:"Patent Filing Support",


    // ── HOME PAGE ────────────────────────────────────────────
    home_hero_title: "Reinventing Ideas for Sustainability",
    home_hero_sub: "Where IoT, AI & Robotics Come Together",
    home_hero_btn1: "Explore Our Products", home_hero_btn2: "Explore Kiosk",
    ind_ems: "EMS", ind_robotics: "Robotics", ind_3dprint: "3D Print Farm",
    ind_ai: "Artificial Intelligence", ind_m2m: "Machine to Machine",
    ind_proddev: "Product Development", ind_allservices: "All Services",
    home_latest_news: "Latest News", learn_more_btn: "Learn More",
    home_feature_cat: "SMART SECURE SEAMLESS CONTROL SYSTEM",
    home_feature_title: "Transforming Shutter Access with Automation",
    home_feature_desc: "MySafeShutter is an automation system designed by MyAccess to improve the way rolling shutters are operated in shops, garages, and industrial spaces. By combining mechanical reliability with modern electronic control, the system enhances safety, convenience, and operational efficiency while supporting the growing need for automated access solutions.",
    home_news1_cat: "PROTOTYPE, PRINT, AND PRODUCE WITH PRECISION",
    home_news1_title: "3D Print Farm: Advanced 3D Printing For Prototyping And Production",
    home_news2_cat: "CENTRALIZED CONTROL FOR CONNECTED DEVICES",
    home_news2_title: "Smart Kiosk: Digital Control Center For Environment Control",
    home_news3_cat: "SMART WAY TO MANAGE BUSINESS IN ONE PLATFORM",
    home_news3_title: "Modular ERP: Structured Digital System For Business Management",
    home_read_all_news: "READ ALL NEWS >",
    home_solve_title: "Solve Complex Challenges",
    home_solve_sub: "with MyAccess expertise.",
    home_explore_services: "Explore all Services",
    home_biocompat: "BIOCOMPATIBLE Class I and Class II with Form 4B",
    home_make_anything: "Make Anything",
    home_make_anything_sub: "With MYACCESS Capabilities",
    tab_products: "Products", tab_auxiliary: "Auxiliary Products",
    tab_giveaway: "Giveaway Products", tab_lab: "Laboratory And Farms", tab_skill: "Skill Enhancement",
    home_rapid_title: "Rapid Prototyping",
    home_rapid_desc: "Turn your ideas into high-fidelity prototypes that look and work like final products within a day and bring better products to market faster.",
    home_watch_webinar: "WATCH THE WEBINAR NOW >",
    home_concept: "Concept Exploration", home_looks: "Looks-Like Prototyping",
    home_functional: "Functional Prototyping", home_validation: "Product Validation",
    home_get_in_touch: "Get In Touch",
    aux_hero_title:"",aux_hero_desc:"",aux_link:"",aux_item1:"",aux_item2:"",aux_item3:"",aux_item4:"",
    giveaway_hero_title:"",giveaway_hero_desc:"",giveaway_link:"",giveaway_item1:"",giveaway_item2:"",giveaway_item3:"",giveaway_item4:"",
    lab_hero_title:"",lab_hero_desc:"",lab_link:"",lab_item1:"",lab_item2:"",lab_item3:"",lab_item4:"",
    skill_hero_title:"",skill_hero_desc:"",skill_link:"",skill_item1:"",skill_item2:"",skill_item3:"",skill_item4:"",

    // ── ABOUT PAGE ───────────────────────────────────────────
    about_intro_title: "MyAccess Builds Natural Technology That Turns Ideas into Meaningful Solutions",
    about_intro_p1: "We want to change the perspective of technology to \"Natural Technology\". Our works purely justify that technology doesn't always kill nature. There is always at least a single problem to a solution. We find the problems even to our solutions and reshape the technology to its good side.",
    about_intro_p2: "In order to identify a problem, we first solve it in different ways and then identify different problems. This leaves a margin to gather problems and find an innovative solution that is ever-lasting.",
    about_who_title: "Who We Are",
    about_who_desc: "We as a team don't always have people. We also consider places, machines, thoughts, and things as a team because they help in completing us. We are a team in search of a community, who can lead their thoughts in serving every individual giving a broader scope of life to every individual and making technology the means to keep alive togetherness rather than distancing.",
    about_mission_title: "Our Mission",
    about_mission_desc: "Give each individual the quality of life and time they deserve for a lifetime.",
    about_vision_title: "Our Vision",
    about_vision_desc: "To be the world's best company shaping the technology more to its silver lining.",
    about_see_awards: "See More Awards",
    stat_projects: "Projects Completed", stat_clients: "Clients", stat_years: "Years Experience",
    about_strength1_title: "Strategy", about_strength1_desc: "Prioritize fresh talent rather than early talent without any bias. Youth has the power to make or destroy the weapon called technology.",
    about_strength2_title: "Tactic", about_strength2_desc: "Lending hands in the educational sector is the best tactic to explore and inject thoughts into one's mind.",
    about_strength3_title: "Goal", about_strength3_desc: "The main goal is to provide you with experience and wisdom rather than knowledge.",
    about_our_strength: "Our Strength",
    about_strength_desc: "At MYACCESS PRIVATE LIMITED, we believe every individual has the potential to make a significant impact, yet we embrace the power of teamwork, understanding that together, we achieve more. Our values are steadfast, guiding us reliably through all challenges.",
    about_our_leadership: "Our Leadership",
    leader1_role: "Founder", leader1_bio: "Surya is the visionary driving MYACCESS towards 'Natural Technology.' He focuses on solving complex problems by reshaping technology to align with nature and human needs.",
    leader2_role: "Co-Founder", leader2_bio: "Naveen leads the technical strategy, ensuring that every MYACCESS innovation is built with precision, scalability, and excellence to meet modern industrial demands.",
    about_advisory: "Our Advisory Committee",
    advisor1_role: "GPT Principal", advisor1_bio: "Dr. Shekar provides academic oversight and institutional guidance for cutting-edge research.", advisor1_detailed: "Principal of Government Polytechnic Pendurthi and seasoned Head of the Department at the Department of Technical Education, Andhra Pradesh, brings extensive expertise in Mechanical Engineering to MYACCESS Advisory Committee.",
    advisor2_role: "Professor", advisor2_bio: "With decades of experience, Dr. Krishna advises on technological curricula and student strategies.", advisor2_detailed: "Dr. B.T. Krishna, a Professor of Electronics and Communication Engineering at UCEK, JNTUK, brings expertise in Nanoelectronics and Analog VLSI to our Advisory Committee. An acclaimed scholar and a fellow of IEEE and IETE, his guidance is pivotal in steering MYACCESS PRIVATE LIMITED’s innovative endeavors.",
    advisor3_role: "Assistant Professor", advisor3_bio: "Dr. Chisti focuses on AI implementation and automation logic for robust systems.", advisor3_detailed: "Md Khwaja Moinuddin Chishty, an esteemed Advisory Committee member at MYACCESS PRIVATE LIMITED and Assistant Professor at GITAM University, is an award-winning inventor and expert in AI, machine learning, and embedded systems.",
    advisor4_role: "Associate Professor", advisor4_bio: "Dr. Rao leads our research initiatives in system optimization and sustainable technology.", advisor4_detailed: "Dr. Bhaskara Rao Jammu, an esteemed Advisory Committee member at MYACCESS PRIVATE LIMITED, is also an Associate Professor at GVP College of Engineering. Specializing in ASIC design and FPGA development.",
    about_frontline_title: "Our Frontline Team",
    about_frontline_desc: "At MYACCESS PRIVATE LIMITED, our team of experts leads the charge in technology innovation, harnessing AI, IoT, and automation to improve everyday life.",
    ft1_role: "Frontend & Embedded Developer", ft1_bio: "Builds responsive and dynamic user interfaces using React and develops embedded solutions for smart devices.",
    ft2_role: "Back-End Developer", ft2_bio: "Uses Django to build robust, scalable web applications with deep expertise in data-driven systems.",
    ft3_role: "Hardware Engineer", ft3_bio: "Validates performance and durability of our electronic products through comprehensive stress and functionality tests.",
    ft4_role: "Procurement Engineer", ft4_bio: "Plays a crucial role in sourcing and managing the services that support our technological innovations.",
    ft5_role: "Electronics Engineer", ft5_bio: "Core of our product development. Designs and implements circuitry and systems that power our innovative devices.",
    ft6_role: "Embedded Developer", ft6_bio: "Specializes in developing embedded systems, focusing on reliable hardware integration and efficient technology solutions.",
    ft7_role: "EMS Technician", ft7_bio: "Handles electronic manufacturing and system assembly, ensuring precise component integration and reliable electronic solutions.",
    ft8_role: "Cloud Engineer", ft8_bio: "Builds and manages scalable cloud infrastructure, ensuring secure, reliable, and high-performance systems for modern applications.",
    ft9_role: "Front-End Developer", ft9_bio: "Creates modern, responsive web interfaces focused on performance, usability, and seamless user experience.",
    about_commitment_title: "Our Commitment",
    about_commitment_desc: "At MYACCESS PRIVATE LIMITED, we champion unconventional thinking, urging our team to \"think crazy, not different\" as we believe unique ideas drive progress. We prioritize identifying and solving problems, upholding a strong commitment to excellence and integrity in everything we do.",
    about_community_btn: "Explore Community and Impact Initiatives",


     // ── SALES PAGE ──────────────────────────────────────────────
sales_hero_title: "Contact A MYACCESS Expert",
sales_send_msg: "Send us a message. During business hours, we aim to respond within 10 minutes.",
sales_firstname: "First name", sales_lastname: "Last name",
sales_email: "Business email", sales_phone: "Phone",
sales_country: "Country or Region", sales_select: "— Select —",
sales_howhelp: "How can we help you?",
sales_submit: "Get in Touch",
sales_book_title: "Book a Demo",
sales_book_desc: "Have a specific challenge? Get your questions answered in a one-on-one virtual walkthrough and discover how our products can fit into your specific workflow.",
sales_book_btn: "Book a Live Demo >",
sales_call_title: "Give Us a Call",
sales_col_location: "Location", sales_col_lang: "Languages",
sales_col_phone: "Toll-Free Phone Number", sales_col_hours: "Working Hours",
sales_reseller_title: "Find a Reseller",
sales_reseller_desc: "MYACCESS partners with hundreds of resellers to bring our products to customers around the world.",
sales_reseller_btn: "Find a Local Reseller >",

    // ── COMMUNITY PAGE ──
    comm_hero_title: "Community and Impact",
    comm_hero_sub: "Through initiatives around access, education, and equity, MYACCESS is working to share the resources and tools needed to lift up our communities.",
    comm_card1_cat: "OUTREACH",
    comm_card1_title: "MYACCESS Ed",
    comm_card1_desc: "MYACCESS employees volunteer annually with local schools to teach hands-on engineering courses. Students get mentoring from experts.",
    comm_card1_btn: "LEARN MORE >",
    comm_card2_cat: "CURRICULUM",
    comm_card2_title: "Educator Enablement",
    comm_card2_desc: "Explore resources for teaching engineering, life sciences, and design. Join our Educator Forum for peer-to-peer exchange.",
    comm_card2_btn: "EXPLORE EDUCATOR RESOURCES >",
    comm_card3_cat: "MATERIAL DONATIONS",
    comm_card3_title: "Student Group Sponsorships",
    comm_card3_desc: "MYACCESS invites student groups to request in-kind donations of resins, powders, and consumables to enable hands-on projects.",
    comm_card3_btn: "APPLY FOR SPONSORSHIP >",
    comm_card4_cat: "DISCOUNTS",
    comm_card4_title: "Special Pricing",
    comm_card4_desc: "Accredited educational institutions are eligible for special pricing, including discounts on printers and accessories.",
    comm_card4_btn: "FIND A RESELLER >",
    comm_card5_cat: "PRINTER DONATIONS",
    comm_card5_title: "ReAccess",
    comm_card5_desc: "MYACCESS occasionally donates refurbished hardware to local organizations and non-profits to support innovation.",
    comm_card5_btn: "APPLY FOR HARDWARE DONATION >",
    comm_card6_cat: "OUTREACH",
    comm_card6_title: "Community Tours",
    comm_card6_desc: "We host K-12 and university groups for educational tours. Tours include an introduction to technology and hands-on activities.",
    comm_card6_btn: "EMAIL US >",
    comm_join_title: "Join The Team",
    comm_join_desc: "We are growing rapidly! Find an open role across the world.",
    comm_join_btn: "VIEW OUR CURRENT OPENINGS",

// ── FACTORY SOLUTIONS ──
fs_hero_title: "Factory Solutions",
fs_hero_sub: "Work with MYACCESS to build an additive manufacturing solution for your company's most important production challenges.",
fs_hero_contact: "Contact Sales",
fs_solutions_title: "Production Solutions Built for You",
fs_solutions_sub: "Our offerings are custom-designed to meet your manufacturing needs.",
fs_toc_title: "Table of Contents",
fs_section1_title: "Build Your Fleet",
fs_section2_title: "Production-Grade Materials",
fs_section3_title: "Fleet Automation Tools",
fs_bring_title: "Bring 3D Printing to Production",
fs_bring_p1: "Factory Solutions turns your additive manufacturing goals into reality. Leverage the MYACCESS ecosystem and our production-grade printers, materials, and tools to create digital factories built to adapt and respond to your priorities.",
fs_bring_p2: "Make millions of individually customized parts. Respond to a supply chain shortage. Launch limited edition products. Whether you are planning, scaling, or pivoting production, collaborate with our experts to make 3D printing a growth engine for your business.",
fs_fleet_desc: "MYACCESS makes it simple to deploy and manage a fleet of 3D printers. Our team will work closely with you to define the hardware, software, and consumables best-fit for your needs.",
fs_download_whitepaper: "Download the White Paper",
fs_mat_desc: "We offer the widest range of professional 3D printing materials and can also work with you to create customized, production-ready material specific to your application.",
fs_explore_materials: "Explore Materials",
fs_auto_desc: "Optimize production throughput with tools that manage and monitor your printer fleet for you. Leverage automated workflows to streamline processing and maintenance tasks.",
fs_explore_software: "Explore Our Software Solutions",
fs_ready_title: "Ready to collaborate, develop, and manufacture with MYACCESS?",
fs_ready_btn: "Contact Sales",
fs_card1_desc:"Implementing production 3D printing solutions with services built to enable your success.",
fs_card2_desc:"Work with us to develop a custom material suited for your production goals.",
fs_card3_desc:"Maximize fleet prodcutivity with automation tools that streamline your 3D printing operations.",
fs_hero_contact_line:"Have a production goal in mind? Let's get in touch.",

  },

  TE: {
    // ── HEADER ──────────────────────────────────────────────
    nav_products: "ఉత్పత్తులు", nav_services: "సేవలు", nav_software: "సాఫ్ట్‌వేర్",
    nav_applications: "అప్లికేషన్లు", nav_learn: "నేర్చుకోండి", nav_support: "సహాయం",
    nav_contact: "సంప్రదించండి", find_reseller: "రీసెల్లర్‌ను కనుగొనండి",

    // ── FOOTER ──────────────────────────────────────────────
    enter_email: "అప్‌డేట్‌ల కోసం మీ ఇమెయిల్ నమోదు చేయండి",
    email_placeholder: "బిజినెస్ ఇమెయిల్", copyright: "© MYACCESS 2026",
    privacy: "గోప్యతా విధానం", terms: "సేవా నిబంధనలు", faq: "తరచుగా అడిగే ప్రశ్నలు",
    footer_3dprinters: "3D ప్రింటర్లు", footer_postprocess: "పోస్ట్-ప్రాసెసింగ్",
    footer_materials: "మెటీరియల్స్", footer_software: "సాఫ్ట్‌వేర్",
    footer_industries: "పరిశ్రమలు", footer_learn: "నేర్చుకోండి",
    footer_company: "కంపెనీ", footer_support: "సహాయం", footer_sales: "సేల్స్",

    // ── CONTACT PAGE ────────────────────────────────────────
    contact_title: "మమ్మల్ని సంప్రదించండి",
    contact_sales_title: "సేల్స్ విభాగాన్ని సంప్రదించండి",
    contact_sales_desc: "మీ వ్యాపారానికి సరైన పరిష్కారాలను కనుగొనడంలో మా నిపుణులు మీకు సహాయం చేయడానికి సిద్ధంగా ఉన్నారు.",
    find_reseller_btn: "స్థానిక రీసెల్లర్‌ను కనుగొనండి >",
    contact_support_title: "సహాయం కోసం సంప్రదించండి",
    contact_support_desc: "ఉత్పత్తుల వాడకంపై ఏవైనా ప్రశ్నలు ఉంటే, మా సహాయ వనరులను చూడండి లేదా మమ్మల్ని సంప్రదించండి.",
    visit_support: "మా సపోర్ట్ సైట్‌ను సందర్శించండి >", create_ticket: "సపోర్ట్ టికెట్ సృష్టించండి >",
    contact_general_title: "MYACCESS సంప్రదించండి",
    contact_general_desc: "మీ అనుభవాన్ని మాతో పంచుకోవాలనుకుంటున్నారా? మేము వినడానికి సిద్ధంగా ఉన్నాము.",
    submit_feedback: "ఫీడ్‌బ్యాక్ పంపండి >", offices: "కార్యాలయాలు", show_on_map: "మ్యాప్‌లో చూడండి >",

    // ── INDUSTRIES PAGE ─────────────────────────────────────
    ind_headline: "నిపుణుల కోసం ఖచ్చితమైన మరియు బహుముఖ 3D ప్రింటింగ్",
    ind_subtext: "మీ పరిశ్రమలో మీరు రాణించడానికి Formlabs 3D ప్రింటర్లు రూపొందించబడ్డాయి.",
    select_industry: "మీ సేవను ఎంచుకోండి", learn_more: "మరింత తెలుసుకోండి",
    ind_banner_title: "3D ప్రింటర్ మీ పనిలో ఎలా సహాయపడుతుందో ఆలోచిస్తున్నారా?",
    ind_banner_sub: "నిపుణుడి నుండి ఉచిత సంప్రదింపులను పొందండి.",
    scaling_title: "ఈరోజే మీ ప్రోటోటైపింగ్ మరియు ఉత్పత్తిని ప్రారంభించండి",
    scaling_sub: "మీ వ్యాపారానికి సరైన పరిష్కారాన్ని కనుగొనడానికి మా 3D ప్రింటర్‌లను అన్వేషించండి.",
    explore_printers: "3D ప్రింటర్‌లను అన్వేషించండి",
    ind_solder_rework: "సోల్డరింగ్ & రీవర్క్", ind_pcb_design: "PCB డిజైన్", ind_embedded_development: "ఎంబెడెడ్ డెవలప్‌మెంట్",
    ind_test_debug: "టెస్టింగ్ & డీబగ్గింగ్", ind_compliance_checklist: "ESD కాంప్లియన్స్ చెక్‌లిస్ట్", ind_mechanical_cad: "మెకానికల్ CAD",
    ind_opencpu_firm: "OpenCPU / OpenWRT ఫర్మ్‌వేర్", ind_pcb_fabrication: "PCB ఫ్యాబ్రికేషన్", ind_component_procurement: "కాంపోనెంట్ ప్రొక్యూర్‌మెంట్", ind_ems_assembly: "EMS అసెంబ్లీ",
    ind_3d:"3D ప్రింటింగ్",ind_plastic:"ప్లాస్టిక్ ఇంజెక్షన్ మోల్డింగ్ (PIM)",ind_3d_mold:"3D ప్రింటెడ్ మోల్డ్",ind_mob:"ఫుల్‌స్టాక్ డెవలప్‌మెంట్ (వెబ్ + మొబైల్)",
    ind_cld_service:"క్లౌడ్ సర్వీసెస్",ind_cicd:"CI/CD & DevOps",ind_patent_filing:"పేటెంట్ ఫైలింగ్ సపోర్ట్",

    // ── HOME PAGE ────────────────────────────────────────────
    home_hero_title: "సుస్థిరత కోసం ఆలోచనలను పునర్నిర్మించడం",
    home_hero_sub: "IoT, AI & రోబోటిక్స్ కలిసే చోటు",
    home_hero_btn1: "మా ఉత్పత్తులను అన్వేషించండి", home_hero_btn2: "కియోస్క్ అన్వేషించండి",
    ind_ems: "EMS", ind_robotics: "రోబోటిక్స్", ind_3dprint: "3D ప్రింట్ ఫార్మ్",
    ind_ai: "కృత్రిమ మేధస్సు (AI)", ind_m2m: "మెషిన్ టు మెషిన్",
    ind_proddev: "ప్రొడక్ట్ డెవలప్‌మెంట్", ind_allservices: "అన్ని సేవలు",
    home_latest_news: "తాజా వార్తలు", learn_more_btn: "మరింత తెలుసుకోండి",
    home_feature_cat: "స్మార్ట్ సెక్యూర్ సీమ్‌లెస్ కంట్రోల్ సిస్టమ్",
    home_feature_title: "ఆటోమేషన్‌తో షట్టర్ యాక్సెస్‌ను మార్చడం",
    home_feature_desc: "MySafeShutter అనేది షాపులు, గ్యారేజీలు మరియు పారిశ్రామిక ప్రదేశాలలో రోలింగ్ షట్టర్ల పనితీరును మెరుగుపరచడానికి MyAccess రూపొందించిన ఆటోమేషన్ సిస్టమ్.",
    home_news1_cat: "ఖచ్చితత్వంతో ప్రోటోటైప్, ప్రింట్ మరియు ఉత్పత్తి చేయండి",
    home_news1_title: "3D ప్రింట్ ఫార్మ్: ప్రోటోటైపింగ్ మరియు ఉత్పత్తి కోసం అధునాతన 3D ప్రింటింగ్",
    home_news2_cat: "కనెక్ట్ చేయబడిన పరికరాల కోసం కేంద్రీకృత నియంత్రణ",
    home_news2_title: "స్మార్ట్ కియోస్క్: ఎన్విరాన్‌మెంట్ కంట్రోల్ కోసం డిజిటల్ కంట్రోల్ సెంటర్",
    home_news3_cat: "వ్యాపారాన్ని ఒకే ప్లాట్‌ఫారమ్‌లో నిర్వహించడానికి స్మార్ట్ మార్గం",
    home_news3_title: "మాడ్యులర్ ERP: వ్యాపార నిర్వహణ కోసం నిర్మాణాత్మక డిజిటల్ వ్యవస్థ",
    home_read_all_news: "అన్ని వార్తలను చదవండి >",
    home_solve_title: "క్లిష్టమైన సవాళ్లను పరిష్కరించండి",
    home_solve_sub: "MyAccess నిపుణతతో.",
    home_explore_services: "అన్ని సేవలను అన్వేషించండి",
    home_biocompat: "Form 4B తో బయోకాంపాటిబుల్ Class I మరియు Class II",
    home_make_anything: "ఏదైనా సృష్టించండి",
    home_make_anything_sub: "MYACCESS సామర్థ్యాలతో",
    tab_products: "ఉత్పత్తులు", tab_auxiliary: "అనుబంధ ఉత్పత్తులు",
    tab_giveaway: "గివ్వే ఉత్పత్తులు", tab_lab: "లాబొరేటరీ మరియు ఫార్మ్స్", tab_skill: "నైపుణ్యాల పెంపు",
    home_rapid_title: "రాపిడ్ ప్రోటోటైపింగ్",
    home_rapid_desc: "మీ ఆలోచనలను ఒక్క రోజులోనే తుది ఉత్పత్తుల వలె పనిచేసే ప్రోటోటైప్‌లుగా మార్చండి మరియు మెరుగైన ఉత్పత్తులను వేగంగా మార్కెట్లోకి తీసుకురండి.",
    home_watch_webinar: "వెబ్‌నార్ ఇప్పుడే చూడండి >",
    home_concept: "కాన్సెప్ట్ అన్వేషణ", home_looks: "లుక్స్-లైక్ ప్రోటోటైపింగ్",
    home_functional: "ఫంక్షనల్ ప్రోటోటైపింగ్", home_validation: "ప్రొడక్ట్ వ్యాలిడేషన్",
    home_get_in_touch: "సంప్రదించండి",

    // ── ABOUT PAGE ───────────────────────────────────────────
    about_intro_title: "MyAccess ఆలోచనలను అర్థవంతమైన పరిష్కారాలుగా మార్చే సహజ సాంకేతికతను నిర్మిస్తుంది",
    about_intro_p1: "మేము సాంకేతికత పట్ల దృక్పథాన్ని \"సహజ సాంకేతికత\"గా మార్చాలనుకుంటున్నాము. సాంకేతికత ఎల్లప్పుడూ ప్రకృతిని చంపదని మా పనులు నిరూపిస్తాయి.",
    about_intro_p2: "ఒక సమస్యను గుర్తించడానికి, మేము మొదట దానిని వివిధ మార్గాల్లో పరిష్కరిస్తాము మరియు తరువాత విభిన్న సమస్యలను గుర్తిస్తాము.",
    about_who_title: "మేము ఎవరు",
    about_who_desc: "మేము ఒక కమ్యూనిటీ కోసం వెతుకుతున్న బృందం, వారు ప్రతి వ్యక్తికి సేవ చేయడంలో తమ ఆలోచనలను నడిపించగలరు.",
    about_mission_title: "మా లక్ష్యం",
    about_mission_desc: "ప్రతి వ్యక్తికి జీవితకాలం పాటు వారు అర్హులైన నాణ్యమైన జీవితాన్ని మరియు సమయాన్ని అందించడం.",
    about_vision_title: "మా విజన్",
    about_vision_desc: "సాంకేతికతను మరింత మెరుగైన దిశగా రూపొందించే ప్రపంచంలోని ఉత్తమ కంపెనీగా ఎదగడం.",
    about_see_awards: "మరిన్ని అవార్డులను చూడండి",
    stat_projects: "పూర్తయిన ప్రాజెక్ట్‌లు", stat_clients: "క్లయింట్లు", stat_years: "అనుభవం (సంవత్సరాలు)",
    about_strength1_title: "వ్యూహం", about_strength1_desc: "ఎటువంటి పక్షపాతం లేకుండా పాత ప్రతిభ కంటే తాజా ప్రతిభకు ప్రాధాన్యత ఇవ్వండి.",
    about_strength2_title: "ట్యాక్టిక్", about_strength2_desc: "విద్యా రంగంలో సహాయం చేయడం అనేది ఒకరి మనస్సులో ఆలోచనలను ఇంజెక్ట్ చేయడానికి ఉత్తమ మార్గం.",
    about_strength3_title: "లక్ష్యం", about_strength3_desc: "కేవలం జ్ఞానం కంటే అనుభవాన్ని మరియు జ్ఞానాన్ని (Wisdom) అందించడమే ప్రధాన లక్ష్యం.",
    about_our_strength: "మా బలం",
    about_strength_desc: "MYACCESS PRIVATE LIMITED లో, ప్రతి వ్యక్తికి గొప్ప ప్రభావం చూపే సామర్థ్యం ఉందని మేము నమ్ముతాము.",
    about_our_leadership: "మా నాయకత్వం",
    leader1_role: "వ్యవస్థాపకుడు", leader1_bio: "సూర్య MYACCESS ను 'సహజ సాంకేతికత' వైపు నడిపిస్తున్న దార్శనికుడు.",
    leader2_role: "సహ-వ్యవస్థాపకుడు", leader2_bio: "నవీన్ సాంకేతిక వ్యూహానికి నాయకత్వం వహిస్తారు, ప్రతి ఆవిష్కరణ ఖచ్చితత్వంతో నిర్మించబడేలా చూస్తారు.",
    about_advisory: "మా సలహా కమిటీ",
    advisor1_role: "GPT ప్రిన్సిపాల్", advisor1_bio: "డాక్టర్ శేఖర్ అత్యాధునిక పరిశోధనల కోసం విద్యాపరమైన మార్గదర్శకత్వాన్ని అందిస్తారు.",
    advisor2_role: "ప్రొఫెసర్", advisor2_bio: "దశాబ్దాల అనుభవంతో, డాక్టర్ కృష్ణ సాంకేతిక పాఠ్యాంశాలపై సలహాలు ఇస్తారు.",
    advisor3_role: "అసిస్టెంట్ ప్రొఫెసర్", advisor3_bio: "డాక్టర్ చిస్తీ AI అమలు మరియు ఆటోమేషన్ లాజిక్ పై దృష్టి పెడతారు.",
    advisor4_role: "అసోసియేట్ ప్రొఫెసర్", advisor4_bio: "డాక్టర్ రావు సిస్టమ్ ఆప్టిమైజేషన్ మరియు సుస్థిర సాంకేతికతలో పరిశోధనలను నడిపిస్తారు.",
    about_frontline_title: "మా ఫ్రంట్‌లైన్ టీమ్",
    about_frontline_desc: "MYACCESS PRIVATE LIMITED లో, మా నిపుణుల బృందం రోజువారీ జీవితాన్ని మెరుగుపరచడానికి AI, IoT మరియు ఆటోమేషన్‌ను ఉపయోగిస్తుంది.",
    ft1_role: "ఫ్రంటెండ్ & ఎంబెడెడ్ డెవలపర్", ft1_bio: "React మరియు ఎంబెడెడ్ సొల్యూషన్స్ ఉపయోగించి స్మార్ట్ పరికరాల కోసం ఇంటర్‌ఫేస్‌లను నిర్మిస్తారు.",
    ft2_role: "బ్యాక్-ఎండ్ డెవలపర్", ft2_bio: "Django ఉపయోగించి దృఢమైన, స్కేలబుల్ వెబ్ అప్లికేషన్లను నిర్మిస్తారు.",
    ft3_role: "హార్డ్‌వేర్ ఇంజనీర్", ft3_bio: "మా ఎలక్ట్రానిక్ ఉత్పత్తుల పనితీరు మరియు మన్నికను పరీక్షల ద్వారా ధృవీకరిస్తారు.",
    about_commitment_title: "మా నిబద్ధత",
    about_commitment_desc: "మేము మా బృందాన్ని \"భిన్నంగా కాదు, క్రేజీగా ఆలోచించండి\" అని ప్రోత్సహిస్తాము, ఎందుకంటే ప్రత్యేకమైన ఆలోచనలే ప్రగతిని నడిపిస్తాయని మేము నమ్ముతాము.",
    about_community_btn: "కమ్యూనిటీ మరియు ఇంపాక్ట్ ఇనిషియేటివ్స్ అన్వేషించండి",

    // ── SALES PAGE ──────────────────────────────────────────────
    sales_hero_title: "MYACCESS నిపుణుడిని సంప్రదించండి",
    sales_send_msg: "మాకు సందేశం పంపండి. వ్యాపార సమయాల్లో, మేము 10 నిమిషాల్లో స్పందిస్తాము.",
    sales_firstname: "మొదటి పేరు", sales_lastname: "చివరి పేరు",
    sales_email: "బిజినెస్ ఇమెయిల్", sales_phone: "ఫోన్",
    sales_country: "దేశం లేదా ప్రాంతం", sales_select: "— ఎంచుకోండి —",
    sales_howhelp: "మేము మీకు ఎలా సహాయపడగలము?",
    sales_submit: "సంప్రదించండి",
    sales_book_title: "డెమో బుక్ చేయండి",
    sales_book_desc: "మీ ప్రశ్నలకు ప్రత్యక్ష వర్చువల్ వాక్‌త్రూలో సమాధానాలు పొందండి.",
    sales_book_btn: "లైవ్ డెమో బుక్ చేయండి >",
    sales_call_title: "మాకు కాల్ చేయండి",
    sales_col_location: "ప్రాంతం", sales_col_lang: "భాషలు",
    sales_col_phone: "టోల్-ఫ్రీ ఫోన్ నంబర్", sales_col_hours: "పని వేళలు",
    sales_reseller_title: "రీసెల్లర్‌ను కనుగొనండి",
    sales_reseller_desc: "ప్రపంచవ్యాప్తంగా మా ఉత్పత్తులను అందించడానికి MYACCESS వందలాది రీసెల్లర్‌లతో భాగస్వామ్యం కలిగి ఉంది.",
    sales_reseller_btn: "స్థానిక రీసెల్లర్‌ను కనుగొనండి >",

    // ── COMMUNITY PAGE ──
    comm_hero_title: "కమ్యూనిటీ మరియు ఇంపాక్ట్",
    comm_hero_sub: "అందరికీ సాంకేతికతను అందించడం, విద్య మరియు సమానత్వం ద్వారా మా కమ్యూనిటీలను అభివృద్ధి చేయడానికి MYACCESS కృషి చేస్తోంది.",
    comm_card1_cat: "ఔట్‌రీచ్",
    comm_card1_title: "MYACCESS Ed",
    comm_card1_desc: "MYACCESS ఉద్యోగులు స్థానిక పాఠశాలల్లో ఇంజనీరింగ్ కోర్సులను బోధించడానికి ఏటా వాలంటీర్లుగా పని చేస్తారు.",
    comm_card1_btn: "మరింత తెలుసుకోండి >",
    comm_card2_cat: "పాఠ్యాంశాలు",
    comm_card2_title: "ఎడ్యుకేటర్ ఎనేబుల్‌మెంట్",
    comm_card2_desc: "ఇంజనీరింగ్ మరియు డిజైన్ బోధించడానికి వనరులను అన్వేషించండి. మా ఎడ్యుకేటర్ ఫోరమ్‌లో చేరండి.",
    comm_card2_btn: "వనరులను అన్వేషించండి >",
    comm_card3_cat: "మెటీరియల్ విరాళాలు",
    comm_card3_title: "స్టూడెంట్ గ్రూప్ స్పాన్సర్‌షిప్స్",
    comm_card3_desc: "ప్రాజెక్ట్‌ల కోసం మెటీరియల్ విరాళాలను అభ్యర్థించడానికి విద్యార్థి బృందాలను MYACCESS ఆహ్వానిస్తోంది.",
    comm_card3_btn: "స్పాన్సర్‌షిప్ కోసం దరఖాస్తు చేయండి >",
    comm_card4_cat: "డిస్కౌంట్లు",
    comm_card4_title: "ప్రత్యేక ధరలు",
    comm_card4_desc: "గుర్తింపు పొందిన విద్యా సంస్థలు ప్రింటర్లు మరియు విడిభాగాలపై ప్రత్యేక రాయితీలకు అర్హులు.",
    comm_card4_btn: "రీసెల్లర్‌ను కనుగొనండి >",
    comm_card5_cat: "ప్రింటర్ విరాళాలు",
    comm_card5_title: "ReAccess",
    comm_card5_desc: "ఆవిష్కరణలకు మద్దతుగా MYACCESS అప్పుడప్పుడు స్థానిక సంస్థలకు హార్డ్‌వేర్‌ను విరాళంగా ఇస్తుంది.",
    comm_card5_btn: "విరాళం కోసం దరఖాస్తు చేయండి >",
    comm_card6_cat: "ఔట్‌రీచ్",
    comm_card6_title: "కమ్యూనిటీ టూర్స్",
    comm_card6_desc: "మేము విద్యార్థుల కోసం ఎడ్యుకేషనల్ టూర్లను నిర్వహిస్తాము. ఇందులో సాంకేతిక పరిచయం ఉంటుంది.",
    comm_card6_btn: "మాకు ఇమెయిల్ చేయండి >",
    comm_join_title: "మా బృందంలో చేరండి",
    comm_join_desc: "మేము వేగంగా ఎదుగుతున్నాము! మీ కోసం సరైన ఉద్యోగాన్ని వెతకండి.",
    comm_join_btn: "ఖాళీలను చూడండి",

// ── FACTORY SOLUTIONS ──

fs_hero_title: "ఫ్యాక్టరీ సొల్యూషన్స్",
fs_hero_sub: "మీ కంపెనీ యొక్క అతి ముఖ్యమైన ఉత్పత్తి సవాళ్ల కోసం అడిటివ్ మాన్యుఫ్యాక్చరింగ్ పరిష్కారాన్ని రూపొందించడానికి MYACCESSతో కలిసి పని చేయండి.",
fs_hero_contact: "సేల్స్‌ను సంప్రదించండి",
fs_solutions_title: "మీ కోసం రూపొందించిన ప్రొడక్షన్ సొల్యూషన్స్",
fs_solutions_sub: "మా ఆఫర్‌లు మీ తయారీ అవసరాలకు అనుగుణంగా కస్టమ్-డిజైన్ చేయబడ్డాయి.",
fs_toc_title: "విషయ సూచిక",
fs_section1_title: "మీ ఫ్లీట్‌ను నిర్మించండి",
fs_section2_title: "ప్రొడక్షన్-గ్రేడ్ మెటీరియల్స్",
fs_section3_title: "ఫ్లీట్ ఆటోమేషన్ టూల్స్",
fs_bring_title: "3D ప్రింటింగ్‌ను ఉత్పత్తిలోకి తీసుకురండి",
fs_bring_p1: "ఫ్యాక్టరీ సొల్యూషన్స్ మీ లక్ష్యాలను నిజం చేస్తాయి. మీ ప్రాధాన్యతలకు అనుగుణంగా డిజిటల్ ఫ్యాక్టరీలను రూపొందించడానికి MYACCESS పర్యావరణ వ్యవస్థను మరియు మా ప్రొడక్షన్-గ్రేడ్ ప్రింటర్లను ఉపయోగించండి.",
fs_bring_p2: "లక్షలాది విడిభాగాలను తయారు చేయండి. సరఫరా గొలుసు కొరతకు స్పందించండి. పరిమిత ఎడిషన్ ఉత్పత్తులను ప్రారంభించండి.",
fs_fleet_desc: "3D ప్రింటర్ల ఫ్లీట్‌ను మోహరించడం మరియు నిర్వహించడం MYACCESS సులభతరం చేస్తుంది.",
fs_download_whitepaper: "వైట్ పేపర్‌ను డౌన్‌లోడ్ చేయండి",
fs_mat_desc: "మేము విస్తృత శ్రేణి ప్రొఫెషనల్ 3D ప్రింటింగ్ మెటీరియల్‌లను అందిస్తున్నాము.",
fs_explore_materials: "మెటీరియల్స్ అన్వేషించండి",
fs_auto_desc: "మీ ప్రింటర్ ఫ్లీట్‌ను పర్యవేక్షించే సాధనాలతో ఉత్పత్తిని ఆప్టిమైజ్ చేయండి.",
fs_explore_software: "మా సాఫ్ట్‌వేర్ పరిష్కారాలను అన్వేషించండి",
fs_ready_title: "MYACCESSతో సహకరించడానికి మరియు ఉత్పత్తి చేయడానికి సిద్ధంగా ఉన్నారా?",
fs_ready_btn: "సేల్స్‌ను సంప్రదించండి",
  },
 

  HI: {
    // ── HEADER ──────────────────────────────────────────────
    nav_products: "उत्पाद", nav_services: "सेवाएं", nav_software: "सॉफ़्टवेयर",
    nav_applications: "अनुप्रयोग", nav_learn: "सीखें", nav_support: "सहायता",
    nav_contact: "संपर्क", find_reseller: "रीसेलर खोजें",

    // ── FOOTER ──────────────────────────────────────────────
    enter_email: "अपडेट के लिए ईमेल दर्ज करें",
    email_placeholder: "व्यावसायिक ईमेल", copyright: "© MYACCESS 2026",
    privacy: "गोपनीयता नीति", terms: "सेवा की शर्तें", faq: "सामान्य प्रश्न",
    footer_3dprinters: "3D प्रिंटर", footer_postprocess: "पोस्ट-प्रोसेसिंग",
    footer_materials: "सामग्री", footer_software: "सॉफ़्टवेयर",
    footer_industries: "उद्योग", footer_learn: "सीखें",
    footer_company: "कंपनी", footer_support: "सहायता", footer_sales: "बिक्री",

    // ── CONTACT PAGE ────────────────────────────────────────
    contact_title: "हमसे संपर्क करें",
    contact_sales_title: "बिक्री से संपर्क करें",
    contact_sales_desc: "हमारे विशेषज्ञ आपको सही समाधान खोजने में मदद करने के लिए तैयार हैं।",
    find_reseller_btn: "स्थानीय रीसेलर खोजें >",
    contact_support_title: "सहायता से संपर्क करें",
    contact_support_desc: "उत्पादों के बारे में प्रश्न हैं तो हमारे सहायता संसाधन देखें।",
    visit_support: "हमारी सहायता साइट देखें >", create_ticket: "सहायता टिकट बनाएं >",
    contact_general_title: "MYACCESS से संपर्क करें",
    contact_general_desc: "अपना फीडबैक साझा करना चाहते हैं? हम सुन रहे हैं।",
    submit_feedback: "फीडबैक सबमिट करें >", offices: "कार्यालय", show_on_map: "नक्शे पर दिखाएं >",

    // ── INDUSTRIES PAGE ─────────────────────────────────────
    ind_headline: "उद्योग पेशेवरों के लिए सटीक 3D प्रिंटिंग",
    ind_subtext: "Formlabs 3D प्रिंटर आपके उद्योग में उत्कृष्टता के लिए डिज़ाइन किए गए हैं।",
    select_industry: "अपना उद्योग चुनें", learn_more: "और जानें",
    ind_banner_title: "क्या 3D प्रिंटर आपके काम में मदद कर सकता है?",
    ind_banner_sub: "किसी विशेषज्ञ से निःशुल्क परामर्श प्राप्त करें।",
    scaling_title: "आज ही प्रोटोटाइपिंग शुरू करें",
    scaling_sub: "अपने व्यवसाय के लिए सही समाधान खोजने के लिए हमारे 3D प्रिंटर देखें।",
    explore_printers: "3D प्रिंटर देखें",
    ind_engineering: "इंजीनियरिंग", ind_manufacturing: "विनिर्माण", ind_automotive: "ऑटोमोटिव",
    ind_aerospace: "एयरोस्पेस", ind_dental: "दंत चिकित्सा", ind_medical: "चिकित्सा",
    ind_education: "शिक्षा", ind_entertainment: "मनोरंजन", ind_jewelry: "आभूषण", ind_audio: "ऑडियो",

    // ── HOME PAGE ────────────────────────────────────────────
    home_hero_title: "स्थिरता के लिए विचारों को नया रूप देना",
    home_hero_sub: "जहां IoT, AI और रोबोटिक्स एक साथ आते हैं",
    home_hero_btn1: "हमारे उत्पाद देखें", home_hero_btn2: "कियोस्क देखें",
    ind_ems: "EMS", ind_robotics: "रोबोटिक्स", ind_3dprint: "3D प्रिंट फार्म",
    ind_ai: "कृत्रिम बुद्धिमत्ता", ind_m2m: "मशीन टू मशीन",
    ind_proddev: "उत्पाद विकास", ind_allservices: "सभी सेवाएं",
    home_latest_news: "ताज़ा खबर", learn_more_btn: "और जानें",
    home_feature_cat: "स्मार्ट सुरक्षित नियंत्रण प्रणाली",
    home_feature_title: "स्वचालन के साथ शटर एक्सेस में बदलाव",
    home_feature_desc: "MySafeShutter एक स्वचालन प्रणाली है जिसे MyAccess ने दुकानों, गैरेज और औद्योगिक स्थानों में रोलिंग शटर को बेहतर बनाने के लिए डिज़ाइन किया है।",
    home_news1_cat: "सटीकता के साथ प्रोटोटाइप, प्रिंट और उत्पादन",
    home_news1_title: "3D प्रिंट फार्म: प्रोटोटाइपिंग और उत्पादन के लिए उन्नत 3D प्रिंटिंग",
    home_news2_cat: "कनेक्टेड डिवाइसों के लिए केंद्रीकृत नियंत्रण",
    home_news2_title: "स्मार्ट कियोस्क: पर्यावरण नियंत्रण के लिए डिजिटल नियंत्रण केंद्र",
    home_news3_cat: "एक प्लेटफॉर्म में व्यवसाय प्रबंधन का स्मार्ट तरीका",
    home_news3_title: "मॉड्यूलर ERP: व्यवसाय प्रबंधन के लिए डिजिटल प्रणाली",
    home_read_all_news: "सभी समाचार पढ़ें >",
    home_solve_title: "जटिल चुनौतियां सुलझाएं",
    home_solve_sub: "MyAccess विशेषज्ञता के साथ।",
    home_explore_services: "सभी सेवाएं देखें",
    home_biocompat: "Form 4B के साथ Class I और Class II बायोकम्पैटिबल",
    home_make_anything: "कुछ भी बनाएं",
    home_make_anything_sub: "MYACCESS क्षमताओं के साथ",
    tab_products: "उत्पाद", tab_auxiliary: "सहायक उत्पाद",
    tab_giveaway: "उपहार उत्पाद", tab_lab: "प्रयोगशाला और फार्म", tab_skill: "कौशल वृद्धि",
    home_rapid_title: "रैपिड प्रोटोटाइपिंग",
    home_rapid_desc: "अपने विचारों को एक दिन में उच्च-निष्ठा प्रोटोटाइप में बदलें और बेहतर उत्पाद तेज़ी से बाज़ार में लाएं।",
    home_watch_webinar: "वेबिनार अभी देखें >",
    home_concept: "अवधारणा अन्वेषण", home_looks: "दिखने वाला प्रोटोटाइप",
    home_functional: "कार्यात्मक प्रोटोटाइप", home_validation: "उत्पाद सत्यापन",
    home_get_in_touch: "संपर्क करें",

    // ── ABOUT PAGE ───────────────────────────────────────────
    about_intro_title: "MyAccess प्राकृतिक तकनीक बनाता है जो विचारों को सार्थक समाधानों में बदलती है",
    about_intro_p1: "हम प्रौद्योगिकी के दृष्टिकोण को \"प्राकृतिक प्रौद्योगिकी\" में बदलना चाहते हैं। हमारे काम यह साबित करते हैं कि प्रौद्योगिकी हमेशा प्रकृति को नुकसान नहीं पहुंचाती।",
    about_intro_p2: "किसी समस्या की पहचान करने के लिए, हम पहले उसे अलग-अलग तरीकों से हल करते हैं और फिर अलग-अलग समस्याओं की पहचान करते हैं।",
    about_who_title: "हम कौन हैं",
    about_who_desc: "हम एक ऐसी टीम हैं जो एक समुदाय की तलाश में है, जो अपने विचारों से हर व्यक्ति की सेवा कर सके।",
    about_mission_title: "हमारा मिशन",
    about_mission_desc: "हर व्यक्ति को जीवनभर के लिए जीवन की गुणवत्ता और समय देना।",
    about_vision_title: "हमारी दृष्टि",
    about_vision_desc: "दुनिया की सर्वश्रेष्ठ कंपनी बनना जो प्रौद्योगिकी को उसके अच्छे पक्ष की ओर आकार देती है।",
    about_see_awards: "और पुरस्कार देखें",
    stat_projects: "पूर्ण परियोजनाएं", stat_clients: "ग्राहक", stat_years: "वर्षों का अनुभव",
    about_strength1_title: "रणनीति", about_strength1_desc: "बिना किसी पूर्वाग्रह के नई प्रतिभाओं को प्राथमिकता दें। युवाओं में प्रौद्योगिकी को बनाने या नष्ट करने की शक्ति है।",
    about_strength2_title: "युक्ति", about_strength2_desc: "शैक्षणिक क्षेत्र में मदद करना विचारों को खोजने और मन में डालने का सबसे अच्छा तरीका है।",
    about_strength3_title: "लक्ष्य", about_strength3_desc: "मुख्य लक्ष्य ज्ञान के बजाय अनुभव और ज्ञान प्रदान करना है।",
    about_our_strength: "हमारी शक्ति",
    about_strength_desc: "MYACCESS PRIVATE LIMITED में, हम मानते हैं कि हर व्यक्ति में महत्वपूर्ण प्रभाव डालने की क्षमता है, फिर भी हम टीमवर्क की शक्ति को अपनाते हैं।",
    about_our_leadership: "हमारा नेतृत्व",
    leader1_role: "संस्थापक", leader1_bio: "सूर्य MYACCESS को 'प्राकृतिक प्रौद्योगिकी' की ओर ले जाने वाले दूरदर्शी हैं।",
    leader2_role: "सह-संस्थापक", leader2_bio: "नवीन तकनीकी रणनीति का नेतृत्व करते हैं, यह सुनिश्चित करते हुए कि हर MYACCESS नवाचार सटीकता के साथ बनाया गया है।",
    about_advisory: "हमारी सलाहकार समिति",
    advisor1_role: "GPT प्रधानाचार्य", advisor1_bio: "डॉ. शेखर अत्याधुनिक अनुसंधान के लिए शैक्षणिक देखरेख प्रदान करते हैं।", advisor1_detailed: "Government Polytechnic Pendurthi के प्रधानाचार्य और आंध्र प्रदेश में तकनीकी शिक्षा विभाग के अनुभवी HOD।",
    advisor2_role: "प्रोफेसर", advisor2_bio: "दशकों के अनुभव के साथ, डॉ. कृष्णा तकनीकी पाठ्यक्रम पर सलाह देते हैं।", advisor2_detailed: "UCEK, JNTUK में इलेक्ट्रॉनिक्स और संचार इंजीनियरिंग के प्रोफेसर, नैनोइलेक्ट्रॉनिक्स में विशेषज्ञ।",
    advisor3_role: "सहायक प्रोफेसर", advisor3_bio: "डॉ. चिश्ती AI कार्यान्वयन और स्वचालन तर्क पर ध्यान केंद्रित करते हैं।", advisor3_detailed: "GITAM University में AI, मशीन लर्निंग और एम्बेडेड सिस्टम के विशेषज्ञ।",
    advisor4_role: "एसोसिएट प्रोफेसर", advisor4_bio: "डॉ. राव सिस्टम अनुकूलन में हमारी अनुसंधान पहल का नेतृत्व करते हैं।", advisor4_detailed: "GVP College of Engineering में एसोसिएट प्रोफेसर, ASIC डिजाइन और FPGA विकास में विशेषज्ञ।",
    about_frontline_title: "हमारी अग्रिम पंक्ति टीम",
    about_frontline_desc: "MYACCESS PRIVATE LIMITED में, हमारी विशेषज्ञों की टीम AI, IoT और स्वचालन का उपयोग करके रोजमर्रा की जिंदगी को बेहतर बनाती है।",
    ft1_role: "फ्रंटएंड और एम्बेडेड डेवलपर", ft1_bio: "React का उपयोग करके responsive इंटरफेस और स्मार्ट डिवाइसों के लिए एम्बेडेड समाधान बनाते हैं।",
    ft2_role: "बैक-एंड डेवलपर", ft2_bio: "Django का उपयोग करके robust, scalable वेब एप्लिकेशन बनाते हैं।",
    ft3_role: "हार्डवेयर इंजीनियर", ft3_bio: "व्यापक परीक्षणों के माध्यम से हमारे इलेक्ट्रॉनिक उत्पादों के प्रदर्शन और स्थायित्व को मान्य करते हैं।",
    ft4_role: "खरीद इंजीनियर", ft4_bio: "हमारी तकनीकी नवाचारों का समर्थन करने वाली सेवाओं को सोर्स और प्रबंधित करने में महत्वपूर्ण भूमिका निभाते हैं।",
    ft5_role: "इलेक्ट्रॉनिक्स इंजीनियर", ft5_bio: "उत्पाद विकास के मूल में हैं। हमारे नवीन उपकरणों को शक्ति देने वाले सर्किटरी और सिस्टम डिज़ाइन करते हैं।",
    ft6_role: "एम्बेडेड डेवलपर", ft6_bio: "एम्बेडेड सिस्टम विकसित करने में विशेषज्ञ, हार्डवेयर एकीकरण और कुशल तकनीकी समाधानों पर ध्यान केंद्रित करते हैं।",
    ft7_role: "EMS तकनीशियन", ft7_bio: "इलेक्ट्रॉनिक विनिर्माण और सिस्टम असेंबली संभालते हैं, सटीक घटक एकीकरण सुनिश्चित करते हैं।",
    ft8_role: "क्लाउड इंजीनियर", ft8_bio: "आधुनिक अनुप्रयोगों के लिए सुरक्षित, विश्वसनीय और उच्च-प्रदर्शन प्रणाली सुनिश्चित करते हुए scalable cloud infrastructure बनाते हैं।",
    ft9_role: "फ्रंट-एंड डेवलपर", ft9_bio: "प्रदर्शन, उपयोगिता और seamless उपयोगकर्ता अनुभव पर केंद्रित आधुनिक, responsive वेब इंटरफेस बनाते हैं।",
    about_commitment_title: "हमारी प्रतिबद्धता",
    about_commitment_desc: "MYACCESS PRIVATE LIMITED में, हम अपरंपरागत सोच का समर्थन करते हैं, अपनी टीम को \"पागल सोचो, अलग नहीं\" के लिए प्रोत्साहित करते हैं क्योंकि हमें विश्वास है कि अनूठे विचार प्रगति को प्रेरित करते हैं।",
    about_community_btn: "सामुदायिक और प्रभाव पहलों का अन्वेषण करें",

      // ── SALES PAGE ──────────────────────────────────────────────
sales_hero_title: "3D प्रिंटिंग विशेषज्ञ से संपर्क करें",
sales_send_msg: "हमें एक संदेश भेजें। व्यावसायिक घंटों के दौरान, हम 10 मिनट के भीतर जवाब देने का लक्ष्य रखते हैं।",
sales_firstname: "पहला नाम", sales_lastname: "अंतिम नाम",
sales_email: "व्यावसायिक ईमेल", sales_phone: "फ़ोन",
sales_country: "देश या क्षेत्र", sales_select: "— चुनें —",
sales_howhelp: "हम आपकी कैसे मदद कर सकते हैं?",
sales_submit: "संपर्क करें",
sales_book_title: "डेमो बुक करें",
sales_book_desc: "कोई विशेष चुनौती है? एक-पर-एक वर्चुअल वॉकथ्रू में अपने प्रश्नों के उत्तर पाएं।",
sales_book_btn: "लाइव डेमो बुक करें >",
sales_call_title: "हमें कॉल करें",
sales_col_location: "स्थान", sales_col_lang: "भाषाएं",
sales_col_phone: "टोल-फ्री फ़ोन नंबर", sales_col_hours: "कार्य घंटे",
sales_reseller_title: "रीसेलर खोजें",
sales_reseller_desc: "MYACCESS दुनिया भर में ग्राहकों तक उत्पाद पहुंचाने के लिए सैकड़ों रीसेलर के साथ साझेदारी करता है।",
sales_reseller_btn: "स्थानीय रीसेलर खोजें >",


// ── COMMUNITY PAGE ──
    comm_hero_title: "समुदाय और प्रभाव",
    comm_hero_sub: "पहुंच, शिक्षा और समानता की पहल के माध्यम से, MYACCESS हमारे समुदायों को ऊपर उठाने के लिए आवश्यक संसाधनों और उपकरणों को साझा करने के लिए काम कर रहा है।",
    comm_card1_cat: "आउटरीच",
    comm_card1_title: "MYACCESS एड",
    comm_card1_desc: "MYACCESS के कर्मचारी व्यावहारिक इंजीनियरिंग पाठ्यक्रम सिखाने के लिए स्थानीय स्कूलों के साथ सालाना स्वयंसेवा करते हैं। छात्रों को विशेषज्ञों से परामर्श मिलता है।",
    comm_card1_btn: "और जानें >",
    comm_card2_cat: "पाठ्यक्रम",
    comm_card2_title: "शिक्षक सशक्तिकरण",
    comm_card2_desc: "इंजीनियरिंग, जीवन विज्ञान और डिजाइन सिखाने के लिए संसाधनों का पता लगाएं। विचारों के आदान-प्रदान के लिए हमारे एजुकेटर फोरम में शामिल हों।",
    comm_card2_btn: "शिक्षक संसाधन देखें >",
    comm_card3_cat: "सामग्री दान",
    comm_card3_title: "छात्र समूह प्रायोजन",
    comm_card3_desc: "MYACCESS छात्र समूहों को व्यावहारिक परियोजनाओं के लिए राल, पाउडर और उपभोग्य सामग्रियों के दान का अनुरोध करने के लिए आमंत्रित करता है।",
    comm_card3_btn: "प्रायोजन के लिए आवेदन करें >",
    comm_card4_cat: "छूट",
    comm_card4_title: "विशेष मूल्य निर्धारण",
    comm_card4_desc: "मान्यता प्राप्त शैक्षणिक संस्थान विशेष मूल्य निर्धारण के पात्र हैं, जिसमें प्रिंटर और सहायक उपकरण पर छूट शामिल है।",
    comm_card4_btn: "रीसेलर खोजें >",
    comm_card5_cat: "प्रिंटर दान",
    comm_card5_title: "ReAccess (री-एक्सेस)",
    comm_card5_desc: "MYACCESS नवाचार का समर्थन करने के लिए स्थानीय संगठनों और गैर-लाभकारी संस्थाओं को कभी-कभी नवीनीकृत हार्डवेयर दान करता है।",
    comm_card5_btn: "हार्डवेयर दान के लिए आवेदन करें >",
    comm_card6_cat: "आउटरीच",
    comm_card6_title: "सामुदायिक भ्रमण",
    comm_card6_desc: "हम शैक्षिक भ्रमण के लिए स्कूल और विश्वविद्यालय समूहों की मेजबानी करते हैं। इसमें प्रौद्योगिकी का परिचय और व्यावहारिक गतिविधियाँ शामिल हैं।",
    comm_card6_btn: "हमें ईमेल करें >",
    comm_join_title: "टीम में शामिल हों",
    comm_join_desc: "हम तेजी से बढ़ रहे हैं! दुनिया भर में खुली भूमिकाएं खोजें।",
    comm_join_btn: "वर्तमान रिक्तियां देखें",

    // ── FACTORY SOLUTIONS ──
    fs_hero_title: "फैक्ट्री सॉल्यूशंस",
fs_hero_sub: "अपनी कंपनी की सबसे महत्वपूर्ण उत्पादन चुनौतियों के लिए समाधान बनाने के लिए MYACCESS के साथ काम करें।",
fs_hero_contact: "बिक्री से संपर्क करें",
fs_solutions_title: "आपके लिए निर्मित उत्पादन समाधान",
fs_solutions_sub: "हमारी पेशकश आपकी विनिर्माण आवश्यकताओं को पूरा करने के लिए डिज़ाइन की गई हैं।",
fs_toc_title: "विषय सूची",
fs_section1_title: "अपना बेड़ा (Fleet) बनाएं",
fs_section2_title: "उत्पादन-ग्रेड सामग्री",
fs_section3_title: "बेड़ा स्वचालन उपकरण",
fs_bring_title: "3D प्रिंटिंग को उत्पादन में लाएं",
fs_bring_p1: "फैक्ट्री सॉल्यूशंस आपके लक्ष्यों को वास्तविकता में बदलते हैं। अपनी प्राथमिकताओं के अनुसार डिजिटल कारखाने बनाने के लिए हमारे उत्पादन-ग्रेड प्रिंटर और टूल का उपयोग करें।",
fs_bring_p2: "लाखों कस्टमाइज्ड पुर्जे बनाएं। आपूर्ति श्रृंखला की कमी का समाधान करें।",
fs_fleet_desc: "MYACCESS 3D प्रिंटर के बेड़े को तैनात करना और प्रबंधित करना आसान बनाता है।",
fs_download_whitepaper: "श्वेत पत्र डाउनलोड करें",
fs_mat_desc: "हम पेशेवर 3D प्रिंटिंग सामग्री की विस्तृत श्रृंखला पेश करते हैं।",
fs_explore_materials: "सामग्री देखें",
fs_auto_desc: "अपने प्रिंटर बेड़े की निगरानी करने वाले उपकरणों के साथ उत्पादन को अनुकूलित करें।",
fs_explore_software: "हमारे सॉफ़्टवेयर समाधान देखें",
fs_ready_title: "क्या आप MYACCESS के साथ सहयोग और निर्माण के लिए तैयार हैं?",
fs_ready_btn: "बिक्री से संपर्क करें",
  },

 

  TA: {
    // ── HEADER ──────────────────────────────────────────────
    nav_products: "தயாரிப்புகள்", nav_services: "சேவைகள்", nav_software: "மென்பொருள்",
    nav_applications: "பயன்பாடுகள்", nav_learn: "கற்றுக்கொள்", nav_support: "ஆதரவு",
    nav_contact: "தொடர்பு", find_reseller: "மறுவிற்பனையாளரை கண்டறியுங்கள்",

    // ── FOOTER ──────────────────────────────────────────────
    enter_email: "புதுப்பிப்புகளுக்கு மின்னஞ்சல் உள்ளிடுங்கள்",
    email_placeholder: "வணிக மின்னஞ்சல்", copyright: "© MYACCESS 2026",
    privacy: "தனியுரிமை கொள்கை", terms: "சேவை விதிமுறைகள்", faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    footer_3dprinters: "3D அச்சுப்பொறிகள்", footer_postprocess: "பிந்தைய செயலாக்கம்",
    footer_materials: "பொருட்கள்", footer_software: "மென்பொருள்",
    footer_industries: "தொழில்கள்", footer_learn: "கற்றுக்கொள்",
    footer_company: "நிறுவனம்", footer_support: "ஆதரவு", footer_sales: "விற்பனை",

    // ── CONTACT PAGE ────────────────────────────────────────
    contact_title: "எங்களை தொடர்பு கொள்ளுங்கள்",
    contact_sales_title: "விற்பனையை தொடர்பு கொள்ளுங்கள்",
    contact_sales_desc: "உங்கள் வணிகத்திற்கு சரியான தீர்வுகளை கண்டறிய எங்கள் நிபுணர்கள் தயாராக உள்ளனர்.",
    find_reseller_btn: "உள்ளூர் மறுவிற்பனையாளரை கண்டறியுங்கள் >",
    contact_support_title: "ஆதரவை தொடர்பு கொள்ளுங்கள்",
    contact_support_desc: "தயாரிப்புகளை பயன்படுத்துவதில் கேள்விகள் இருந்தால், எங்கள் ஆதரவு ஆதாரங்களை பார்க்கவும்.",
    visit_support: "எங்கள் ஆதரவு தளத்தை பார்வையிடுங்கள் >", create_ticket: "ஆதரவு டிக்கெட் உருவாக்கவும் >",
    contact_general_title: "MYACCESS ஐ தொடர்பு கொள்ளுங்கள்",
    contact_general_desc: "உங்கள் கருத்தை பகிர விரும்புகிறீர்களா? நாங்கள் கேட்கிறோம்.",
    submit_feedback: "கருத்தை சமர்ப்பிக்கவும் >", offices: "அலுவலகங்கள்", show_on_map: "வரைபடத்தில் காட்டு >",

    // ── INDUSTRIES PAGE ─────────────────────────────────────
    ind_headline: "தொழில் வல்லுநர்களுக்கான துல்லியமான 3D அச்சிடல்",
    ind_subtext: "Formlabs 3D அச்சுப்பொறிகள் உங்கள் தொழிலில் சிறந்து விளங்க வடிவமைக்கப்பட்டுள்ளன.",
    select_industry: "உங்கள் தொழிலை தேர்ந்தெடுங்கள்", learn_more: "மேலும் அறியுங்கள்",
    ind_banner_title: "3D அச்சுப்பொறி உங்கள் பணிக்கு உதவுமா?",
    ind_banner_sub: "நிபுணரிடம் இலவச ஆலோசனை பெறுங்கள்.",
    scaling_title: "இன்றே உங்கள் உற்பத்தியை அளவிடத் தொடங்குங்கள்",
    scaling_sub: "உங்கள் வணிகத்திற்கு சரியான தீர்வை கண்டறிய எங்கள் 3D அச்சுப்பொறிகளை ஆராயுங்கள்.",
    explore_printers: "3D அச்சுப்பொறிகளை ஆராயுங்கள்",
    ind_engineering: "பொறியியல்", ind_manufacturing: "உற்பத்தி", ind_automotive: "வாகனம்",
    ind_aerospace: "வான்வெளி", ind_dental: "பல் மருத்துவம்", ind_medical: "மருத்துவம்",
    ind_education: "கல்வி", ind_entertainment: "பொழுதுபோக்கு", ind_jewelry: "நகைகள்", ind_audio: "ஒலி",

    // ── HOME PAGE ────────────────────────────────────────────
    home_hero_title: "நிலைத்தன்மைக்காக யோசனைகளை மறுவடிவமைத்தல்",
    home_hero_sub: "IoT, AI மற்றும் ரோபாட்டிக்ஸ் ஒன்றாக வரும் இடம்",
    home_hero_btn1: "எங்கள் தயாரிப்புகளை ஆராயுங்கள்", home_hero_btn2: "கியோஸ்க் ஆராயுங்கள்",
    ind_ems: "EMS", ind_robotics: "ரோபாட்டிக்ஸ்", ind_3dprint: "3D பிரிண்ட் பண்ணை",
    ind_ai: "செயற்கை நுண்ணறிவு", ind_m2m: "இயந்திரம் முதல் இயந்திரம்",
    ind_proddev: "தயாரிப்பு மேம்பாடு", ind_allservices: "அனைத்து சேவைகள்",
    home_latest_news: "சமீபத்திய செய்திகள்", learn_more_btn: "மேலும் அறியுங்கள்",
    home_feature_cat: "ஸ்மார்ட் பாதுகாப்பான கட்டுப்பாட்டு அமைப்பு",
    home_feature_title: "தானியங்கியுடன் ஷட்டர் அணுகலை மாற்றுதல்",
    home_feature_desc: "MySafeShutter என்பது MyAccess ஆல் வடிவமைக்கப்பட்ட ஒரு தானியங்கி அமைப்பு.",
    home_news1_cat: "துல்லியத்துடன் மாதிரி, அச்சிடு மற்றும் உற்பத்தி செய்யுங்கள்",
    home_news1_title: "3D பிரிண்ட் பண்ணை: மேம்பட்ட 3D அச்சிடல்",
    home_news2_cat: "இணைக்கப்பட்ட சாதனங்களுக்கு மையப்படுத்தப்பட்ட கட்டுப்பாடு",
    home_news2_title: "ஸ்மார்ட் கியோஸ்க்: சுற்றுச்சூழல் கட்டுப்பாடு மையம்",
    home_news3_cat: "ஒரு தளத்தில் வணிகத்தை நிர்வகிக்க ஸ்மார்ட் வழி",
    home_news3_title: "மட்டு ERP: வணிக நிர்வாகத்திற்கான கட்டமைக்கப்பட்ட டிஜிட்டல் அமைப்பு",
    home_read_all_news: "அனைத்து செய்திகளையும் படியுங்கள் >",
    home_solve_title: "சிக்கலான சவால்களை தீர்க்கவும்",
    home_solve_sub: "MyAccess நிபுணத்துவத்துடன்.",
    home_explore_services: "அனைத்து சேவைகளையும் ஆராயுங்கள்",
    home_biocompat: "Form 4B உடன் Class I மற்றும் Class II உயிரியல் இணக்கம்",
    home_make_anything: "எதையும் உருவாக்குங்கள்",
    home_make_anything_sub: "MYACCESS திறன்களுடன்",
    tab_products: "தயாரிப்புகள்", tab_auxiliary: "துணை தயாரிப்புகள்",
    tab_giveaway: "பரிசு தயாரிப்புகள்", tab_lab: "ஆய்வகம் மற்றும் பண்ணைகள்", tab_skill: "திறன் மேம்பாடு",
    home_rapid_title: "விரைவு மாதிரியாக்கம்",
    home_rapid_desc: "உங்கள் யோசனைகளை ஒரு நாளில் உயர்தர மாதிரிகளாக மாற்றி சந்தையில் வேகமாக கொண்டு வாருங்கள்.",
    home_watch_webinar: "வெபினரை இப்போது பாருங்கள் >",
    home_concept: "கருத்து ஆய்வு", home_looks: "தோற்ற மாதிரியாக்கம்",
    home_functional: "செயல்பாட்டு மாதிரியாக்கம்", home_validation: "தயாரிப்பு சரிபார்ப்பு",
    home_get_in_touch: "தொடர்பு கொள்ளுங்கள்",

    // ── ABOUT PAGE ───────────────────────────────────────────
    about_intro_title: "MyAccess இயற்கை தொழில்நுட்பத்தை உருவாக்குகிறது",
    about_intro_p1: "நாங்கள் தொழில்நுட்பத்தின் கண்ணோட்டத்தை 'இயற்கை தொழில்நுட்பமாக' மாற்ற விரும்புகிறோம்.",
    about_intro_p2: "ஒரு சிக்கலை அடையாளம் காண, நாங்கள் முதலில் அதை வெவ்வேறு வழிகளில் தீர்க்கிறோம்.",
    about_who_title: "நாங்கள் யார்",
    about_who_desc: "நாங்கள் ஒரு சமூகத்தை தேடும் குழு, எல்லா தனிநபர்களுக்கும் சேவை செய்ய தங்கள் எண்ணங்களை வழிநடத்தக்கூடியவர்கள்.",
    about_mission_title: "எங்கள் நோக்கம்",
    about_mission_desc: "ஒவ்வொரு தனிநபருக்கும் வாழ்நாள் முழுவதும் அவர்கள் தகுதியான வாழ்க்கை தரம் மற்றும் நேரம் வழங்குங்கள்.",
    about_vision_title: "எங்கள் தொலைநோக்கு",
    about_vision_desc: "தொழில்நுட்பத்தை அதன் நல்ல பக்கத்தை நோக்கி வடிவமைக்கும் உலகின் சிறந்த நிறுவனமாக இருக்க வேண்டும்.",
    about_see_awards: "மேலும் விருதுகளைப் பாருங்கள்",
    stat_projects: "முடிக்கப்பட்ட திட்டங்கள்", stat_clients: "வாடிக்கையாளர்கள்", stat_years: "ஆண்டுகள் அனுபவம்",
    about_strength1_title: "உத்தி", about_strength1_desc: "எந்த சார்பும் இல்லாமல் புதிய திறமைகளுக்கு முன்னுரிமை கொடுங்கள்.",
    about_strength2_title: "தந்திரம்", about_strength2_desc: "கல்வி துறையில் உதவுவது எண்ணங்களை மனதில் ஆராய்ந்து செலுத்த சிறந்த வழி.",
    about_strength3_title: "இலக்கு", about_strength3_desc: "முக்கிய இலக்கு அறிவை விட அனுபவம் மற்றும் ஞானம் வழங்குவது.",
    about_our_strength: "எங்கள் பலம்",
    about_strength_desc: "MYACCESS PRIVATE LIMITED இல், ஒவ்வொரு தனிநபருக்கும் குறிப்பிடத்தக்க தாக்கத்தை ஏற்படுத்தும் திறன் இருப்பதாக நம்புகிறோம்.",
    about_our_leadership: "எங்கள் தலைமை",
    leader1_role: "நிறுவனர்", leader1_bio: "Surya MYACCESS ஐ 'இயற்கை தொழில்நுட்பம்' நோக்கி வழிநடத்தும் தொலைநோக்காளர்.",
    leader2_role: "இணை நிறுவனர்", leader2_bio: "Naveen தொழில்நுட்ப உத்தியை வழிநடத்துகிறார், ஒவ்வொரு MYACCESS கண்டுபிடிப்பும் துல்லியத்துடன் கட்டமைக்கப்படுவதை உறுதிசெய்கிறார்.",
    about_advisory: "எங்கள் ஆலோசனைக் குழு",
    advisor1_role: "GPT முதல்வர்", advisor1_bio: "டாக்டர் Shekar அத்யாவசிய ஆராய்ச்சிக்கு கல்வி மேற்பார்வை வழங்குகிறார்.", advisor1_detailed: "Government Polytechnic Pendurthi முதல்வர் மற்றும் ஆந்திரப் பிரதேசத்தில் தொழில்நுட்ப கல்வி துறையின் HOD.",
    advisor2_role: "பேராசிரியர்", advisor2_bio: "பல தசாப்தங்களின் அனுபவத்துடன், டாக்டர் கிருஷ்ணா தொழில்நுட்ப பாடத்திட்டங்களில் ஆலோசனை வழங்குகிறார்.", advisor2_detailed: "UCEK, JNTUK இல் மின்னணு மற்றும் தகவல் தொடர்பு பொறியியல் பேராசிரியர்.",
    advisor3_role: "உதவி பேராசிரியர்", advisor3_bio: "டாக்டர் Chisti AI செயல்படுத்தல் மற்றும் தானியங்கி தர்க்கத்தில் கவனம் செலுத்துகிறார்.", advisor3_detailed: "GITAM பல்கலைக்கழகத்தில் AI, மெஷின் லேர்னிங் மற்றும் எம்பெடட் சிஸ்டம்களில் நிபுணர்.",
    advisor4_role: "இணை பேராசிரியர்", advisor4_bio: "டாக்டர் Rao அமைப்பு உகப்பாக்கத்தில் எங்கள் ஆராய்ச்சி முயற்சிகளை வழிநடத்துகிறார்.", advisor4_detailed: "GVP College of Engineering இல் இணை பேராசிரியர், ASIC வடிவமைப்பில் நிபுணர்.",
    about_frontline_title: "எங்கள் முன்னணி குழு",
    about_frontline_desc: "MYACCESS PRIVATE LIMITED இல், எங்கள் நிபுணர்கள் குழு AI, IoT மற்றும் தானியங்கியைப் பயன்படுத்தி அன்றாட வாழ்க்கையை மேம்படுத்துகிறது.",
    ft1_role: "ஃப்ரண்டெண்ட் மற்றும் எம்பெடட் டெவலப்பர்", ft1_bio: "React ஐ பயன்படுத்தி responsive இடைமுகங்கள் மற்றும் ஸ்மார்ட் சாதனங்களுக்கு எம்பெடட் தீர்வுகளை உருவாக்குகிறார்.",
    ft2_role: "பேக்-எண்ட் டெவலப்பர்", ft2_bio: "Django ஐ பயன்படுத்தி robust, scalable வலை பயன்பாடுகளை உருவாக்குகிறார்.",
    ft3_role: "வன்பொருள் பொறியாளர்", ft3_bio: "விரிவான சோதனைகள் மூலம் எங்கள் மின்னணு தயாரிப்புகளின் செயல்திறனை சரிபார்க்கிறார்.",
    ft4_role: "கொள்முதல் பொறியாளர்", ft4_bio: "எங்கள் தொழில்நுட்ப கண்டுபிடிப்புகளை ஆதரிக்கும் சேவைகளை சோர்ஸ் செய்வதில் முக்கிய பங்கு வகிக்கிறார்.",
    ft5_role: "மின்னணு பொறியாளர்", ft5_bio: "எங்கள் கண்டுபிடிப்பு சாதனங்களுக்கு சக்தி அளிக்கும் சர்க்யூட்ரி மற்றும் அமைப்புகளை வடிவமைக்கிறார்.",
    ft6_role: "எம்பெடட் டெவலப்பர்", ft6_bio: "எம்பெடட் சிஸ்டம்கள் உருவாக்குவதில் நிபுணர், வன்பொருள் ஒருங்கிணைப்பில் கவனம் செலுத்துகிறார்.",
    ft7_role: "EMS தொழில்நுட்பவியலாளர்", ft7_bio: "மின்னணு உற்பத்தி மற்றும் சிஸ்டம் அசம்பிளியை கையாள்கிறார்.",
    ft8_role: "கிளவுட் பொறியாளர்", ft8_bio: "நவீன பயன்பாடுகளுக்கு பாதுகாப்பான, நம்பகமான கிளவுட் உள்கட்டமைப்பை உருவாக்குகிறார்.",
    ft9_role: "ஃப்ரண்ட்-எண்ட் டெவலப்பர்", ft9_bio: "செயல்திறன், பயன்பாட்டு தன்மை மற்றும் seamless பயனர் அனுபவத்தில் கவனம் செலுத்தும் நவீன வலை இடைமுகங்களை உருவாக்குகிறார்.",
    about_commitment_title: "எங்கள் அர்ப்பணிப்பு",
    about_commitment_desc: "MYACCESS PRIVATE LIMITED இல், நாங்கள் மரபுக்கு மாறான சிந்தனையை ஆதரிக்கிறோம், எங்கள் குழுவை 'வித்தியாசமாக அல்ல, பைத்தியமாக சிந்திக்க' ஊக்குவிக்கிறோம்.",
    about_community_btn: "சமூக மற்றும் தாக்கம் முயற்சிகளை ஆராயுங்கள்",


    
  // ── SALES PAGE ──────────────────────────────────────────────
sales_hero_title: "3D பிரிண்டிங் நிபுணரை தொடர்பு கொள்ளுங்கள்",
sales_send_msg: "எங்களுக்கு ஒரு செய்தி அனுப்புங்கள். வேலை நேரங்களில், 10 நிமிடங்களுக்குள் பதிலளிக்க முயற்சிக்கிறோம்.",
sales_firstname: "முதல் பெயர்",
sales_lastname: "கடைசி பெயர்",
sales_email: "வணிக மின்னஞ்சல்",
sales_phone: "தொலைபேசி",
sales_country: "நாடு அல்லது பகுதி",
sales_select: "— தேர்வு செய்யவும் —",
sales_howhelp: "நாங்கள் உங்களுக்கு எப்படி உதவலாம்?",
sales_submit: "தொடர்பு கொள்ளுங்கள்",
sales_book_title: "டெமோ பதிவு செய்யுங்கள்",
sales_book_desc: "உங்களுக்கு ஏதேனும் குறிப்பிட்ட சவால் உள்ளதா? ஒருவருக்கு ஒருவர் மெய்நிகர் விளக்கத்தில் உங்கள் கேள்விகளுக்கான பதில்களை பெறுங்கள்.",
sales_book_btn: "நேரடி டெமோ பதிவு செய்யுங்கள் >",
sales_call_title: "எங்களை அழைக்கவும்",
sales_col_location: "இடம்",
sales_col_lang: "மொழிகள்",
sales_col_phone: "டோல்-ஃப்ரீ தொலைபேசி எண்",
sales_col_hours: "பணிநேரம்",
sales_reseller_title: "மீள்விற்பனையாளரை கண்டுபிடிக்கவும்",
sales_reseller_desc: "MYACCESS உலகம் முழுவதும் உள்ள வாடிக்கையாளர்களுக்கு தயாரிப்புகளை வழங்க நூற்றுக்கணக்கான மீள்விற்பனையாளர்களுடன் கூட்டாண்மை செய்கிறது.",
sales_reseller_btn: "உள்ளூர் மீள்விற்பனையாளரை கண்டுபிடிக்கவும் >",

// ── COMMUNITY PAGE ──
    comm_hero_title: "சமூகம் மற்றும் தாக்கம்",
    comm_hero_sub: "அணுகல், கல்வி மற்றும் சமத்துவம் குறித்த முன்முயற்சிகள் மூலம், எங்கள் சமூகங்களை மேம்படுத்த தேவையான ஆதாரங்கள் மற்றும் கருவிகளைப் பகிர்ந்து கொள்ள MYACCESS செயல்பட்டு வருகிறது.",
    comm_card1_cat: "அவுட்ரீச் (OUTREACH)",
    comm_card1_title: "MYACCESS கல்வி (Ed)",
    comm_card1_desc: "MYACCESS ஊழியர்கள் உள்ளூர் பள்ளிகளில் பொறியியல் படிப்புகளை கற்பிக்க ஆண்டுதோறும் முன்வருகிறார்கள். மாணவர்கள் நிபுணர்களிடமிருந்து வழிகாட்டுதலைப் பெறுகிறார்கள்.",
    comm_card1_btn: "மேலும் அறிய >",
    comm_card2_cat: "பாடத்திட்டம்",
    comm_card2_title: "ஆசிரியர் அதிகாரமளித்தல்",
    comm_card2_desc: "பொறியியல், உயிரியல் மற்றும் வடிவமைப்பு கற்பிப்பதற்கான ஆதாரங்களை ஆராயுங்கள். கருத்துப் பரிமாற்றத்திற்காக எங்கள் கல்வியாளர் மன்றத்தில் இணையுங்கள்.",
    comm_card2_btn: "ஆசிரியர் ஆதாரங்களை ஆராயுங்கள் >",
    comm_card3_cat: "பொருள் நன்கொடைகள்",
    comm_card3_title: "மாணவர் குழு ஸ்பான்சர்ஷிப்கள்",
    comm_card3_desc: "மாணவர் குழுக்கள் தங்கள் திட்டங்களுக்காக ரெசின்கள் மற்றும் இதர பொருட்களை நன்கொடையாகப் பெற MYACCESS அழைப்பு விடுக்கிறது.",
    comm_card3_btn: "ஸ்பான்சர்ஷிப்பிற்கு விண்ணப்பிக்கவும் >",
    comm_card4_cat: "தள்ளுபடிகள்",
    comm_card4_title: "சிறப்பு விலை நிர்ணயம்",
    comm_card4_desc: "அங்கீகரிக்கப்பட்ட கல்வி நிறுவனங்கள் பிரிண்டர்கள் மற்றும் பாகங்கள் மீதான தள்ளுபடிகள் உட்பட சிறப்பு விலையைப் பெற தகுதியுடையவை.",
    comm_card4_btn: "மறுவிற்பனையாளரை கண்டறியவும் >",
    comm_card5_cat: "பிரிண்டர் நன்கொடைகள்",
    comm_card5_title: "ReAccess (மறுஅணுகல்)",
    comm_card5_desc: "புதுமைகளை ஆதரிப்பதற்காக உள்ளூர் அமைப்புகளுக்கு MYACCESS அவ்வப்போது புதுப்பிக்கப்பட்ட வன்பொருள்களை (Hardware) வழங்குகிறது.",
    comm_card5_btn: "நன்கொடைக்கு விண்ணப்பிக்கவும் >",
    comm_card6_cat: "அவுட்ரீச் (OUTREACH)",
    comm_card6_title: "சமூக சுற்றுப்பயணங்கள்",
    comm_card6_desc: "கல்விச் சுற்றுப்பயணங்களுக்காக பள்ளி மற்றும் பல்கலைக்கழக குழுக்களை நாங்கள் வரவேற்கிறோம். இதில் தொழில்நுட்ப அறிமுகம் மற்றும் செயல்பாடுகள் அடங்கும்.",
    comm_card6_btn: "மின்னஞ்சல் செய்யவும் >",
    comm_join_title: "எங்கள் குழுவில் இணையுங்கள்",
    comm_join_desc: "நாங்கள் வேகமாக வளர்ந்து வருகிறோம்! உலகம் முழுவதும் எங்களுடன் இணைந்து பணியாற்ற வாய்ப்புகளைத் தேடுங்கள்.",
    comm_join_btn: "வேலை வாய்ப்புகளைப் பார்க்கவும்",

// ── FACTORY SOLUTIONS ──
fs_hero_title: "தொழிற்சாலை தீர்வுகள் (Factory Solutions)",
fs_hero_sub: "உங்கள் நிறுவனத்தின் முக்கியமான உற்பத்தி சவால்களுக்கு தீர்வுகளை உருவாக்க MYACCESS உடன் இணைந்து பணியாற்றுங்கள்.",
fs_hero_contact: "விற்பனையை தொடர்பு கொள்ளவும்",
fs_solutions_title: "உங்களுக்காக உருவாக்கப்பட்ட உற்பத்தி தீர்வுகள்",
fs_solutions_sub: "எங்கள் சலுகைகள் உங்கள் உற்பத்தித் தேவைகளைப் பூர்த்தி செய்யும் வகையில் வடிவமைக்கப்பட்டுள்ளன.",
fs_toc_title: "பொருளடக்கம்",
fs_section1_title: "உங்கள் கடற்படையை (Fleet) உருவாக்குங்கள்",
fs_section2_title: "உற்பத்தி-தர பொருட்கள்",
fs_section3_title: "தானியங்கி கருவிகள்",
fs_bring_title: "3D பிரிண்டிங்கை உற்பத்திக்கு கொண்டு வாருங்கள்",
fs_bring_p1: "பேக்டரி சொல்யூஷன்ஸ் உங்கள் இலக்குகளை நனவாக்குகின்றன. உங்கள் முன்னுரிமைகளுக்கு ஏற்ப டிஜிட்டல் தொழிற்சாலைகளை உருவாக்க MYACCESS இன் பிரிண்டர்கள் மற்றும் கருவிகளைப் பயன்படுத்தவும்.",
fs_bring_p2: "மில்லியன் கணக்கான பாகங்களை உருவாக்குங்கள். விநியோகச் சங்கிலி பற்றாக்குறையைச் சமாளியுங்கள்.",
fs_fleet_desc: "3D பிரிண்டர்களின் கடற்படையை வரிசைப்படுத்துவதையும் நிர்வகிப்பதையும் MYACCESS எளிதாக்குகிறது.",
fs_download_whitepaper: "வெள்ளை அறிக்கையைப் பதிவிறக்கவும்",
fs_mat_desc: "நாங்கள் பரந்த அளவிலான தொழில்முறை 3D பிரிண்டிங் பொருட்களை வழங்குகிறோம்.",
fs_explore_materials: "பொருட்களை ஆராயுங்கள்",
fs_auto_desc: "உங்கள் பிரிண்டர் கடற்படையைக் கண்காணிக்கும் கருவிகள் மூலம் உற்பத்தியை மேம்படுத்துங்கள்.",
fs_explore_software: "எங்கள் மென்பொருள் தீர்வுகளை ஆராயுங்கள்",
fs_ready_title: "MYACCESS உடன் இணைந்து செயல்படவும் தயாரிக்கவும் தயாரா?",
fs_ready_btn: "விற்பனையை தொடர்பு கொள்ளவும்",
  },

};



const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("EN");
  const t = (key) => translations[lang]?.[key] ?? translations["EN"]?.[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
